name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/cashier.farhandev.cloud
            git pull origin main
            docker build -t superindo-cashier:latest .

            # Check if the docker build command was successful
            if [ $? -ne 0 ]; then
              echo "Docker build failed"
              exit 1  # This will exit the script with an error code
            fi

            docker rm -f superindo-cashier
            docker run -d --name superindo-cashier -p 3006:3000 superindo-cashier:latest
